"""init

Revision ID: 636923eb3e25
Revises: 
Create Date: 2026-03-26 21:04:23.040853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636923eb3e25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fedresurs_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('last_date', sa.DateTime(), nullable=True),
    sa.Column('document_name', sa.String(length=500), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn')
    )
    op.create_table('kad_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('last_date', sa.DateTime(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.Column('fedresurs_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fedresurs_id'], ['fedresurs_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kad_records')
    op.drop_table('fedresurs_records')
    # ### end Alembic commands ###
