"""init

Revision ID: e5ae9caa97b5
Revises: 
Create Date: 2026-03-26 10:34:36.769114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ae9caa97b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fedresurs_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=True),
    sa.Column('last_date', sa.DateTime(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn', name='uix_fedresurs_inn')
    )
    op.create_table('kad_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('last_date', sa.DateTime(), nullable=True),
    sa.Column('document_name', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number', name='uix_kad_case')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kad_records')
    op.drop_table('fedresurs_records')
    # ### end Alembic commands ###
